### PR TITLE
Resolves #610

### LINKED ISSUE #610: Configure globally
It would be good if we could set global defaults for the configuration, particularly for `language`

`$.fn.yadcf.defaults = {}`

I think it would just be a simple case of adding `$.extend({}, $.fn.yadcf.defaults, params)` here https://github.com/vedmack/yadcf/blob/master/dist/jquery.dataTables.yadcf.js#L4642

### PR DESCRIPTION
**Pull request by bytestream**
Usage:
```js
    yadcf.setDefaults({
        language: {
            'filter': 'Escribe para filtrar',
        }
    });
```

### CODE REVIEW

**Comment by bytestream** [comment]
@vedmack any chances of seeing this merged/released soon? 🤞

**Comment by vedmack** [comment]
Please add fallback for users of prev version of yadcf (read from `params.language` and put the values into the `default_options.language` + console.log message saying "please use the new API before calling ytadcf... etc', make it clear for users that used to use the old API that it is deprecated and will be obsolete in the future"  for this in the parts of the code that used to read language param `if (params.language !== undefined) {` and set it into the defaults

**Comment by vedmack** [comment]
Please add fallback for users of prev version of yadcf (read from `params.language` and put the values into the `default_options.language` + console.log message saying "please use the new API before calling ytadcf... etc', make it clear for users that used to use the old API that it is deprecated and will be obsolete in the future"  for this in the parts of the code that used to read language param `if (params.language !== undefined) {` and set it into the defaults
In addition, please post a jsfiddle test page showing how your new code works (minimal example)

**Comment by bytestream** [comment]
@vedmack I don't think that's necessary? The changes are fully BC. If you use `params.language` then it still works the same as before. The only difference is that this PR allows you to configure options without initialisation.

https://jsfiddle.net/7zfuscmt/

Above shows both old way and new way.

**Comment by vedmack** [comment]
ok, cool, then add a bit of documentation at the bottom of the `External API functions:` section

**Comment by vedmack** [comment]
will release a new version in a day or two, thanks for the PR

**Comment by bytestream** [comment]
Woha that was fast 😅 

Thanks :)

**Comment by vedmack** [comment]
changed it into initDefaults, and no need for 'strings'
you can use values `yadcf.initDefaults({language: {select: 'Pick some'}});`

```
* initDefaults
                Description:        Set global defaults for all yadcf instances.
                Arguments:          Object consisting of anything defined under "Global Parameters"
                Usage example:      yadcf.initDefaults({language: {select: 'Pick some'}});
```

**Pull request merged**
