### PR TITLE
fix for bugs in PR #555

### PR DESCRIPTION
**Pull request by misanek**
#555 had bugs: 
* filtering without render function not working due to wrong ternary condition  `aData = rowDataRender ? rowDataRender : rowData;` correct `aData = rowDataRender.length ? rowDataRender : rowData;`

* when we have nested objects in row  => `getProp(rowDataRender, index)`

* updated dt render function with all arguments : https://datatables.net/reference/option/columns.render
@vedmack I am passing meta object to render function, which should have according to docs these properties: 
settings : DtSetting,
col : column index,
row: row index - not sure if I am setting correct one here, from debugging i came up with `row: iDataIndex,` please check if correct thanks :)

### CODE REVIEW

**Comment by vedmack** [comment]
Hey @misanek can you please show me a jsfiddle in which the previous solution didn't worked ?

**Comment by misanek** [comment]
#555 fiddle: http://jsfiddle.net/sr7wtLoy/1/

first 2 columns have render function, filtering works, last 2 are without render function filtering is not working

fiddle with PR code : http://jsfiddle.net/cqu3e5vt/

**Comment by misanek** [comment]
jsFiddle from #555:    http://jsfiddle.net/ne5u42xj/

fist 2 columns have render function, middle 2 don't  , last two have nested data source, first one has render function.

fiddle with PR changes : http://jsfiddle.net/74ms9uhk/1/

**Comment by vedmack** [comment]
thanks @misanek , merging right now because current version seems to be messed from previous PR, hopefully will review it properly this week,

Thanks

**Pull request merged**
