### PR TITLE
Possible to use jQueryUI datepicker or Bootstrap Datepicker

### PR DESCRIPTION
**Pull request by vertoo**
In my project I don't use jQueryUI datepicker, instead of this plugin I use [Bootstrap Datepicker](https://github.com/Eonasdan/bootstrap-datetimepicker).

In example-bootstrap-datepicker.html I include some libraries (bootstrap datepicker, momentjs, jquery), don't look at file locations, this is only my quick example.

Maybe this changes can be useful for someone.

### CODE REVIEW

**Comment by vedmack** [comment]
Thanks, did you implement it for both dates filter types? `date` and `range_date`?

**Comment by vertoo** [comment]
For `date` I will implement today. For jQueryUI Datepicker I will change code to min/max dates for `range_date`.

**Comment by vedmack** [comment]
ok , thanks.

Why change the current code (it works fine) also please use the moment only in code related to the *bootstrap-datetimepicker*

**Comment by vedmack** [comment]
@vertoo , I noticed the following comment "// this code must be fired as event trigger" in your code? while for the jquery ui there is code that is fired `onSelect` for the bootstrap there is only comment?

**Comment by vertoo** [comment]
I know, this code isn't stupid because it's empty if. But bootstrap datapicker don't have option like "onSelect", this must be done after init with events (line 1409-1420)

**Comment by vedmack** [comment]
care to take a look on what i did wrong? because it behave weird when a date picker is being opened (notice that I already modified you original code a bit linted it a bit and renamed properties)
https://dl.dropboxusercontent.com/u/55621125/yadcf/war14/example-bootstrap-datepicker.html

**Comment by vertoo** [comment]
I don't see any broken changes in my original code. Maybe bootstrap-theme
make difference?

Pozdrawiam
  *Grzegorz Gąsak*
www: vertoo.pl
email: info@vertoo.pl
tel: +48 721 954 335

2015-07-14 21:11 GMT+02:00 Daniel <notifications@github.com>:

**Comment by vedmack** [comment]
It was a wrong bootstrap css that I included (already deleted my post but it made its way to you email :) )

**Comment by vedmack** [comment]
Thanks, for the PR, after the merge I will update the datetimepicker related code, so read the docs, I tuned up your code and aligned it with current yadcf style...

**Pull request merged**
