### PR TITLE
Formatting, minor code fixes and typos

### PR DESCRIPTION
**Pull request by m417z**
The first commit is larger, but it contains only whitespace changes.

### CODE REVIEW

**Review by louking — COMMENTED** [review]
When I saw the spelling fix for class yadcf-filter-range-date-seperator I got very nervous that maybe my code is using that. After quick search in my repos, I don't see it in my code, but this type of change has the potential to break other folks' code which may use that class, I think.

**Comment by m417z** [comment]
@louking it has a pretty narrow usage, only for date filtering, so the chances are low, but you're right that it can potentially break somebody's custom code.

I can either revert this part, or it can be documented in the release notes of the next version. Let's see what @vedmack says.

**Comment by vedmack** [comment]
Hi @m417z 
Except for the class typo fix all looks great, please revert the class renaming and I will merge it

**Comment by vedmack** [comment]
@m417z  Just noticed that there are conflicts, robably because I have committed a fix fir the js file

**Comment by vedmack** [comment]
@m417z I resolved the conflicts in the js file, so no problems merging (after you revert the css class typo back)

**Comment by m417z** [comment]
Done, I also added the fix you reverted.

**Pull request merged**
