### PR TITLE
Fixed issue of improper undefined check against settingsDt.aanFeatures.f

### PR DESCRIPTION
**Pull request by mpdas108**
Discovered this issue when trying to reset filters on a server side implementation.

### CODE REVIEW

**Comment by vedmack** [comment]
thx, but please add this fix only in src folder

**Comment by mpdas108** [comment]
I have added to only the src folder now.

**Comment by vedmack** [comment]
@mpdas108 
b.t.w, what issue exactly does the previous undefined check introduced?

**Comment by mpdas108** [comment]
This problem is only applicable to those using server side filtering.

`settingsDt.aanFeatures.f` is not properly seen as undefined so the conditional statement returns true when it should return false. This causes the script to wrongly enter the conditional block and the script produces an error visible in the console when trying to execute the next line which tries to check the length of `settingsDt.aanFeatures.f` :

`for (i = 0; i < settingsDt.aanFeatures.f.length; i++) {` , 

The error is thrown then because `settingsDt.aanFeatures.f` is actually undefined. The result of this error is that the filters are physically reset, but the server is not queried again for results, leaving an empty table.

**Comment by vedmack** [comment]
but typeof should be checked against 'undefined' (wrapped with an apostrophe) ?

**Comment by mpdas108** [comment]
My mistake, in my live version I do have quotes. I forgot them in my local version that I used to submit the PR.

**Comment by mpdas108** [comment]
I also understand that `variable === undefined`, and `variable !== undefined` should work. but for some reason I kept getting undefined errors, meaning the `if (settingsDt.aanFeatures.f !== undefined) {` was failing to detect undefined.

**Comment by mpdas108** [comment]
I added the quotes.

**Comment by vedmack** [comment]
Thanks for the fix,
I guess it happened because in your scenario `f` was not declared in `settingsDt.aanFeatures.f`

**Pull request merged**
