### PR TITLE
Added support to momentjs in amd and commonjs environments.

### PR DESCRIPTION
**Pull request by McGiogen**
This code will load momentjs when and if needed.
I tested this with Webpack and everything is working as expected. I'm pretty confident this works also with CommonJs and I hope it works also with AMD.
This is the best I can achieve with my little experience.
This completes #356.

### CODE REVIEW

**Comment by vedmack** [comment]
Hi,

Instead of multiple call for `loadMoment();` you should call it only once if date/range_date filters are being defined in setup of yadcf, so I'd day you better call the `loadMoment();` once in the `function init(oTable, options_arg, params) {`  above the `if ($(instance.selector).length === 1) {` line, add there something like `loadMomentIfNeeded();` inside which you will iterate over filters and see if  date/range_date filter was used and if so, then call the `if (!moment && ((typeof define === 'function' &&....` code, that way it will be cleaner and more efficient, also, please update only the yadcf js file inside the `src` folder , the yadcf .js in the root is a stable version while the `src` is for beta versions

Thanks

**Comment by McGiogen** [comment]
I will do those changes asap. Meanwhile you can reopen this pull request because I will continue to work on the same branch amending this pull request's commit.

**Comment by McGiogen** [comment]
I've fixed this pull request finally, sorry for the delay. My IDE has automagically deleted some tabs/spaces, I hope it is not a problem.

**Comment by vedmack** [comment]
Hi,

Instead of the `loadMomentIfNeeded` I will provide you to call your own function that will be provided to the yadcf and will be invoked right away, after my commit you will add some more code related to the `moment` module, so stay tuned.
Thanks,

Daniel.

**Pull request closed without merging**
