### PR TITLE
PR for #566 and #567

### PR DESCRIPTION
**Pull request by misanek**
jsfiddle: http://jsfiddle.net/t8y1egz7/  - client side 
server side tested locally 

please check , since it is slightly bigger PR

### CODE REVIEW

**Comment by vedmack** [comment]
Ohhh, a really big one here 👍 
I don't mind with the null feature, but IMO having "null" in you UI is really bad idea unless you table is for technical users only (even then I bet people prefer not to bump into nulls in their browser) It looks like some error, you better re consider showing null.
Please show the [ ] checkbox in the same side (right or left) for all filters, otherwise the behavior is confusing, user should know where to expect those check box/es to appear

**Comment by misanek** [comment]
@vedmack  Thanks for feedback, the check-boxes appear on the correct side, they are set with `checkbox_position_after: true/false` parameter, and for sake of an example, they ware set differently for different columns ( example comes from my testing page, where I wanted to verify, that the reset all button resets checkboxes as well , and on the both sides ).

**Comment by konuch** [comment]
Hey @vedmack ,
unfortunately, our tool is indeed used by technical users, they use it to set values into a configuration DB. Other systems that rely on this configuration, behave differently when we set NULL value, or 'NULL' string value for a given attribute. The users know this, and they want to also be able to filter by NULL values for text filters/range filters for server side tables.
Thanks for taking the effort to review our contributions and also for your comments. 👍

**Comment by vedmack** [comment]
closing since @misanek sent PR https://github.com/vedmack/yadcf/pull/570

**Pull request closed without merging**
