### PR TITLE
Allow to inject JQuery object like DataTable do 

### PR DESCRIPTION
**Pull request by n-rodriguez**
Fix https://github.com/vedmack/yadcf/issues/446

### CODE REVIEW

**Comment by vedmack** [comment]
Thanks but please send the PR for the following path/file */src/jquery.dataTables.yadcf.js*

**Comment by n-rodriguez** [comment]
sure!

**Comment by vedmack** [comment]
@n-rodriguez but please fork it again because I did a commit several minutes ago and your copy is outdated,
thanks!

**Comment by n-rodriguez** [comment]
Done!

**Comment by vedmack** [comment]
tx!

**Comment by n-rodriguez** [comment]
Thanks!

**Pull request merged**
